services:
  mtaamall_frontend:
    container_name: mtaamall-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
    image: mtaamall-frontend:latest
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - mtaamall-public

networks:
  mtaamall-public:
    external: true
