import { useContext, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { ArrowRightIcon, MinusIcon, PlusIcon, ShoppingBagIcon, TrashIcon } from '@heroicons/react/24/outline'
import { CartContext } from '@contexts/CartContext'
import { useAuth } from '@hooks/useAuth'
import { money } from '../../customer/AccountPages'

const CartPage = () => {
  const cart = useContext(CartContext)!
  const { user } = useAuth()
  const location = useLocation()
  const inAccount = location.pathname.startsWith('/account')
  const [error, setError] = useState('')
  const run = async (action: () => Promise<void>) => { setError(''); try { await action() } catch (e: any) { setError(e?.response?.data?.message || e?.message || 'Unable to update cart.') } }
  const line = (item: { id: string; name: string; price: number; quantity: number }, currency = 'KES') => <li key={item.id} className="flex flex-col gap-4 border-b border-divider py-5 first:pt-0 last:border-0 last:pb-0 sm:flex-row sm:items-center">
    <div className="flex min-w-0 flex-1 items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary-dark"><ShoppingBagIcon className="h-6 w-6" /></span><div className="min-w-0"><p className="truncate font-bold text-text">{item.name}</p><p className="text-sm text-text-secondary">{money(item.price, currency)} each</p></div></div>
    <div className="flex items-center justify-between gap-3 sm:justify-end"><div className="flex items-center rounded-xl border border-border bg-background p-1"><button className="grid h-8 w-8 place-items-center rounded-lg text-text-secondary transition hover:bg-white hover:text-primary-dark disabled:opacity-30" aria-label={'Decrease ' + item.name} disabled={cart.isBusy || item.quantity <= 1} onClick={() => run(() => cart.updateQuantity(item.id, item.quantity - 1))}><MinusIcon className="h-4 w-4" /></button><span className="w-9 text-center text-sm font-bold text-text">{item.quantity}</span><button className="grid h-8 w-8 place-items-center rounded-lg text-text-secondary transition hover:bg-white hover:text-primary-dark disabled:opacity-30" aria-label={'Increase ' + item.name} disabled={cart.isBusy} onClick={() => run(() => cart.updateQuantity(item.id, item.quantity + 1))}><PlusIcon className="h-4 w-4" /></button></div><button aria-label={'Remove ' + item.name} className="grid h-9 w-9 place-items-center rounded-xl text-text-tertiary transition hover:bg-error/5 hover:text-error" disabled={cart.isBusy} onClick={() => run(() => cart.removeItem(item.id))}><TrashIcon className="h-5 w-5" /></button></div>
  </li>
  return <div className={inAccount ? '' : 'mx-auto max-w-6xl px-4 py-10'}><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary-dark">Ready when you are</p><h2 className="mt-1 text-2xl font-bold text-text sm:text-3xl">Your carts</h2><p className="mt-1 text-sm text-text-secondary">Items are grouped by seller for simple, accurate checkout.</p></div><Link to="/products" className="inline-flex w-fit items-center gap-2 text-sm font-bold text-primary-dark hover:underline">Continue shopping<ArrowRightIcon className="h-4 w-4" /></Link></div>
    {cart.isBusy && <p role="status">Syncing your cart…</p>}
    {(cart.error || error) && <div role="alert" className="my-4 rounded-xl bg-amber-50 p-4">{cart.error || error} <button className="underline" disabled={cart.isBusy} onClick={() => cart.refresh()}>Retry sync</button></div>}
    {cart.error && cart.pendingGuestItems.length > 0 && <section className="my-4 rounded-xl border p-4"><h3 className="font-semibold">Guest items not yet merged</h3><p className="text-sm">{cart.canEditPendingGuest ? 'Nothing from this batch was added. Remove unavailable items, then retry.' : 'The last attempt has an uncertain outcome. Retry sync before changing these items.'}</p>{cart.pendingGuestItems.map(i => <div key={i.id} className="flex justify-between py-2"><span>{i.name} × {i.quantity}</span><button disabled={cart.isBusy || !cart.canEditPendingGuest} className="underline" onClick={() => cart.removePendingGuestItem(i.id)}>Remove from guest cart</button></div>)}</section>}
    {!cart.isBusy && !cart.error && cart.items.length === 0 && <section className="rounded-2xl border border-border bg-white p-10 text-center shadow-sm"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-primary/10 text-primary-dark"><ShoppingBagIcon className="h-8 w-8" /></span><h3 className="mt-4 text-lg font-bold text-text">Your cart is empty</h3><p className="mt-1 text-sm text-text-secondary">Discover something useful from businesses around you.</p><Link to="/products" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary-dark px-5 py-2.5 text-sm font-bold text-white">Explore products<ArrowRightIcon className="h-4 w-4" /></Link></section>}
    {user ? <div className="space-y-5">{cart.carts.map(c => <section key={c.business_id} className="overflow-hidden rounded-2xl border border-border bg-white shadow-[0_12px_36px_rgba(30,43,50,0.06)]"><header className="flex items-center justify-between gap-4 border-b border-divider bg-gradient-to-r from-primary/5 to-secondary/5 px-5 py-4 sm:px-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-text-tertiary">Seller</p><h3 className="text-lg font-bold text-text">{c.business_name}</h3></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-text-secondary shadow-sm">{c.items.length} product{c.items.length === 1 ? '' : 's'}</span></header><ul className="px-5 py-5 sm:px-6">{c.items.map(i => line({ id: String(i.id), name: i.name, price: i.unit_price, quantity: i.quantity }, c.currency))}</ul>{c.items.some(i => !i.available) && <p className="mx-5 mb-4 rounded-xl bg-warning-light/50 px-4 py-3 text-sm font-medium text-warning-dark sm:mx-6">Remove unavailable products before checkout.</p>}<footer className="flex flex-col gap-4 border-t border-divider bg-background/70 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="text-xs text-text-tertiary">Seller subtotal</p><p className="text-xl font-bold text-text">{money(c.total_amount, c.currency)}</p></div><Link className="inline-flex items-center justify-center gap-2 rounded-xl bg-secondary px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-secondary-dark" to={'/account/checkout?business=' + c.business_id}>Checkout this seller<ArrowRightIcon className="h-4 w-4" /></Link></footer></section>)}</div> :
      <section className="rounded-2xl border bg-white p-5"><ul>{cart.items.map(i => line(i))}</ul><p className="my-4 text-sm text-slate-500">Guest prices are estimates. Sign in to validate availability and prices and separate your cart by seller.</p><Link className="inline-block rounded-lg bg-slate-900 px-4 py-2 text-white" to="/login">Sign in to checkout</Link></section>}
  </div>
}
export default CartPage
